Lazy load commands
doctrine/doctrine-website pull request #362
Opened 2020-09-25 21:11 UTC by greg0ire

Making the command name available without instantiating it makes it
possible to find the right command without instantiating all of them.

2020-09-25 21:38 UTC, ostrolucky approved these changes

2020-09-26 19:06 UTC, SenseException requested changes

2020-09-26 19:06 UTC, SenseException commented on lib/Commands/ClearBuildCacheCommand.php
> +    protected static $defaultName = 'clear-build-cache';
`setName('clear-build-cache')` is still there.

2020-09-26 19:13 UTC, SenseException approved these changes

2020-09-26 19:35 UTC, merged