Temporary(?) fix for the issue #378
doctrine/doctrine-website pull request #379
Opened 2021-01-21 10:05 UTC by mdogancay

This will fix the branchName control mechanism in the /lib/DataBuilder/ProjectDataBuilder.php#isProjectVersionEquals() function 
and side effects /lib/ProcessFactory.php. It gives flexibility in compiling to the project. After all, this project is a documentation and there is no critical damage. Fixing the issue #378.

2021-01-21 21:31 UTC, SenseException requested changes
The question mark in the title is correct. This will be a temporary fix, but it will get us some time. Thanks for the pull request.

Please also fix the code sniffer errors in the code.

2021-01-21 21:31 UTC, SenseException commented on lib/ProcessFactory.php
> +        // This code is used to run the git checkout command.
This is afaik on purpose and we should keep it that way for the moment.

2021-01-21 21:31 UTC, SenseException commented on lib/DataBuilder/ProjectDataBuilder.php
> +        return false;
```suggestion
        if (! isset($b['branchName'])) {
            return false;
        }

        return $a['branchName'] === ($b['branchName']);
```

`$a` contains the data from the repository and will have the `branchName`.

2021-01-30 15:32 UTC, mdogancay commented
I no longer believe that the people leading the Doctrine are kind and good people. For this reason, I stop supporting Doctrine projects and using them in my new works. With this PR, you can do whatever you want. I will not waste any more time for the Doctrine projects. Goodbye...
[Look at here](https://github.com/doctrine/orm/issues/8444)

2021-01-30 18:11 UTC, SenseException commented
Despite your resolution, thanks for starting this PR. I'll take over from here.

2021-02-02 08:41 UTC, SenseException commented
Closed in favour of #383.

2021-02-02 08:41 UTC, closed without merging