Doctrine and OpenCollective
doctrine/doctrine-website pull request #444
Opened 2022-03-24 15:55 UTC by beberlei

2022-03-24 18:00 UTC, malarzm approved these changes
🎉

2022-03-24 20:01 UTC, SenseException requested changes

2022-03-24 20:01 UTC, SenseException commented on source/blog/2022-03-24-opencollective.md
> +  3-4 days of accomodation, food and travel for roughly 10-15 people.
```suggestion
- Regularly organize hackathons for Doctrine Core team contributors, including
  3-4 days of accommodation, food and travel for roughly 10-15 people.
```

2022-03-24 20:01 UTC, SenseException commented on source/blog/2022-03-24-opencollective.md
> +- Marketing material such as stickers, t-shirts, other small things.
```suggestion
- Marketing material such as stickers, t-shirts and other small things.
```

2022-03-24 21:45 UTC, greg0ire commented on source/blog/2022-03-24-opencollective.md
> +motiviated by the success and positive experience of the new PHP Foundation.
```suggestion
motivated by the success and positive experience of the new PHP Foundation.
```

2022-03-24 21:45 UTC, greg0ire commented on source/blog/2022-03-24-opencollective.md
> +gettogethers/hackathons, but due to the pandemic we haven't been able to do this.
```suggestion
get-togethers/hackathons, but due to the pandemic we haven't been able to do this.
```

2022-03-25 07:41 UTC, greg0ire approved these changes

2022-03-25 08:55 UTC, merged